### ISSUE TITLE
Elegir el enfoque

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/JCSD-2016#1]

**Comment by iblancasa** [comment]
@JJ propone explicar qué es la computación voluntaria

Estaría bien. Usando https://github.com/JJ/splash-volunteer como ejemplo principal y qué se hace

**Comment by JJ** [comment]
Yo creo que tampoco habría que ir mucho más allá. Se puede hacer algún
experimento adicional.

**Comment by iblancasa** [comment]
Venga. Entonces decidido

**Comment by iblancasa** [comment]
Teniendo en cuenta el enfoque y que entra en "Demostraciones de herramientas y sistemas software", hay que ver exactamente de qué se va a hablar.
1. Introducción
2. Qué es la computación voluntaria ([este enlace creo que es interesante en cuanto a cosas que deberíamos tratar en esta sección](http://boinc.berkeley.edu/trac/wiki/VolunteerComputing]))
3. Un ejemplo: Splash-Volunteer
4. Otros ejemplos

No sé cómo lo ves, pero tampoco tengo muy claro por dónde empezar

**Comment by iblancasa** [comment]
Voy a empezar por:
1. Motivación 
2. Estado del arte
3. Descripción del splash-volunteer
   1. Cómo se hacen los experimentos

y ya voy viendo
