### ISSUE TITLE
Framework - Marco de aplicaciones/desarrollo?

### ISSUE THREAD

**Issue by 29antonioac** [iblancasa/JCSD-2016#14]
Deberíamos poner en todos lados lo mismo, ¿No? No es coherente ahora mismo, en el título está "Marco de aplicaciones", en la introducción "marco de desarrollo" y en muchos sitios "framework". ¿Con qué nos quedamos?

**Comment by iblancasa** [comment]
Marco. Ahora lo arreglo.
