### ISSUE TITLE
Margen derecho en las palabras clave

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/JCSD-2016#19]
La segunda línea de las palabras clave sobrepasa el margen derecho. Como los términos “computación en internet” y “computación nube” son similares, quizás se debería eliminar el primero y dejar solo el de “computación en la nube”.

**Comment by 29antonioac** [comment]
https://github.com/iblancasa/JCSD-2016/pull/24/commits/c6e3b1eaf66fca9b780a0600d01634fb75c3cf93
