### ISSUE TITLE
Decidir categoría

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/JCSD-2016#2]
En base a #1 tenemos que elegir entre:
1. Trabajos de investigación originales.
2. Trabajos que describan el estado del arte actualizado en cualquiera de los temas de interés para las jornadas.
3. Trabajos publicados recientemente, o pendientes de publicación, en conferencias o revistas.
4. Demostraciones de herramientas y sistemas software.

Ya que

> Se recomienda que los trabajos de las categorías 1, 2 y 4 no excedan de 15 páginas. Para los trabajos de la categoría 3 es suficiente con enviar un resumen del artículo, en el que aparezca el nombre de la conferencia o revista en el que el trabajo ha sido publicado o enviado.

**Comment by JJ** [comment]
Como he dicho en slack, 4.

El 26 de abril de 2016, 21:27, Israel Blancas notifications@github.com
escribió:

> En base a #1 https://github.com/iblancasa/JCSD-2016/issues/1 tenemos
> que elegir entre:
> 1. Trabajos de investigación originales.
> 2. Trabajos que describan el estado del arte actualizado en cualquiera
>    de los temas de interés para las jornadas.
> 3. Trabajos publicados recientemente, o pendientes de publicación, en
>    conferencias o revistas.
> 4. Demostraciones de herramientas y sistemas software.
> 
> Ya que
> 
> Se recomienda que los trabajos de las categorías 1, 2 y 4 no excedan de 15
> páginas. Para los trabajos de la categoría 3 es suficiente con enviar un
> resumen del artículo, en el que aparezca el nombre de la conferencia o
> revista en el que el trabajo ha sido publicado o enviado.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/JCSD-2016/issues/2

## 

JJ

**Comment by iblancasa** [comment]
Perfecto
