### ISSUE TITLE
Encabezado de todas las páginas

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/JCSD-2016#20]
Debe eliminarse el encabezado de todas las páginas.

**Comment by 29antonioac** [comment]
¿Debe borrarse por completo, o debe mostrar el número de página al menos?

**Comment by 29antonioac** [comment]
Aquí también corregí eso https://github.com/iblancasa/JCSD-2016/pull/24/commits/dbd99bd734ad329362d1cfd6b3d3afb71d738ff3

**Comment by iblancasa** [comment]
Yo entiendo que por completo
