### ISSUE TITLE
Palabras que no están en español

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/JCSD-2016#21]
A pesar de estar escrito en español, aparecen algunas palabras en inglés, como “Algorithm”, “Table” y “References”, que sería mejor poner también en español.

**Comment by 29antonioac** [comment]
He podido cambiar "Algorithm", "Table" y "References" por "Algoritmo", "Cuadro" y "Referencias". La primera metiéndole una opción al paquete algorithm y las otras dos con el paquete babel.

Las palabras clave de dentro del algoritmo no las he podido cambiar, le echaré otro vistazo por si en este paquete se puede cambiar

**Comment by 29antonioac** [comment]
https://github.com/iblancasa/JCSD-2016/pull/24/commits/dbd99bd734ad329362d1cfd6b3d3afb71d738ff3
