### ISSUE TITLE
Arreglar referencias

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/JCSD-2016#25]
Todas las referencias deben citarse en el texto. No se citan las referencias que van de la 17 a la 26. Las dos últimas se citan dentro de otras referencias, por lo que sería conveniente poner la información correspondiente en la primera referencia (y así no separar lo que en realidad es una única referencia).

**Comment by iblancasa** [comment]
Me voy a cargar todas las que están sin citar. Lo que no tengo claro es lo de 

> Las dos últimas se citan dentro de otras referencias, por lo que sería conveniente poner la información correspondiente en la primera referencia (y así no separar lo que en realidad es una única referencia).

**Comment by JJ** [comment]
Puedes editar el .bbl y borrarlas, lo que ocurre es que entonces tienes que
editar las citar esas y meterlas enteras. Esto me parece una chorrada, por
cierto...

**Comment by iblancasa** [comment]
No entiendo lo de "citar y meterlas enteras"

**Comment by JJ** [comment]
Insertar la segunda cita (que será el libro o proceedings) dentro de la
primera.

**Comment by iblancasa** [comment]
¿Y cómo lo inserto?

Por ejemplo, Nodeo está referenciado desde Nodio y tengo:

``` latex

@article{nodio,
  title={NodIO, a JavaScript framework for volunteer-based evolutionary algorithms: first results},
  author={Merelo, Juan-J and García-Valdez, Mario and Castillo, Pedro A and García-Sánchez, Pablo and Cuevas, P and Rico, Nuria},
  journal={arXiv preprint arXiv:1601.01607},
  year={2016}
}

@inproceedings{nodeo,
  title={NodEO, a multi-paradigm distributed evolutionary algorithm platform in {JavasSript}},
  author={Merelo, Juan-Julián and Castillo, Pedro and Mora, Antonio and Esparcia-Alcázar, Anna and Rivas-Santos, Víctor},
  booktitle={Proceedings of the 2014 conference companion on Genetic and evolutionary computation companion},
  pages={1155--1162},
  year={2014},
  organization={ACM}
}


```

**Comment by JJ** [comment]
Son dos trabajos diferentes. Déjalo así.
